"""add Combat.active_id

Revision ID: 319bae16dc67
Revises: 48b35a405931
Create Date: 2023-04-22 16:13:23.255589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319bae16dc67'
down_revision = '48b35a405931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combats', sa.Column('active_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'combats', 'crews', ['active_id'], ['id'])
    op.drop_column('combats', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combats', sa.Column('active', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'combats', type_='foreignkey')
    op.drop_column('combats', 'active_id')
    # ### end Alembic commands ###
