"""add Crew.action_comment and Ship.enhance_mobility

Revision ID: 4785c9a6075a
Revises: d07cbbd11c26
Create Date: 2023-04-23 20:50:15.312661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4785c9a6075a'
down_revision = 'd07cbbd11c26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crews', sa.Column('action_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crews', 'sentences', ['action_comment_id'], ['id'])
    op.add_column('ships', sa.Column('enhanced_mobility', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'enhanced_mobility')
    op.drop_constraint(None, 'crews', type_='foreignkey')
    op.drop_column('crews', 'action_comment_id')
    # ### end Alembic commands ###
