"""add Crew.action field

Revision ID: 48b35a405931
Revises: 5e8d53d2f701
Create Date: 2023-04-22 13:09:49.399478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b35a405931'
down_revision = '5e8d53d2f701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crews', sa.Column('action', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crews', 'action')
    # ### end Alembic commands ###
