"""test

Revision ID: 5e8d53d2f701
Revises: 
Create Date: 2023-04-22 12:21:36.389436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8d53d2f701'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'combat_groups', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.alter_column('detail_types', 'string_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'detail_types', ['string_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail_types', type_='unique')
    op.alter_column('detail_types', 'string_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'combat_groups', type_='foreignkey')
    # ### end Alembic commands ###
