"""add ActionKind.Quit

Revision ID: 783a091df9a2
Revises: 4785c9a6075a
Create Date: 2023-04-24 10:20:05.247061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783a091df9a2'
down_revision = '4785c9a6075a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
