"""third try of reimpl combat-crew relationships

Revision ID: 9af95301cdeb
Revises: fba971eb713d
Create Date: 2023-04-22 16:48:51.941367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af95301cdeb'
down_revision = 'fba971eb713d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combat_groups')
    op.drop_constraint('combats_active_id_fkey', 'combats', type_='foreignkey')
    op.drop_column('combats', 'active_id')
    op.add_column('crews', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('crews_combat_id_fkey', 'crews', type_='foreignkey')
    op.drop_column('crews', 'combat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crews', sa.Column('combat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('crews_combat_id_fkey', 'crews', 'combats', ['combat_id'], ['id'])
    op.drop_column('crews', 'active')
    op.add_column('combats', sa.Column('active_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('combats_active_id_fkey', 'combats', 'crews', ['active_id'], ['id'])
    op.create_table('combat_groups',
    sa.Column('combat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crew_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['combat_id'], ['combats.id'], name='combat_groups_combat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='combat_groups_crew_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='combat_groups_crew_id_fkey1', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
