"""reimpl combat-crew relationships

Revision ID: b0a996c54ee4
Revises: 319bae16dc67
Create Date: 2023-04-22 16:21:16.251020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a996c54ee4'
down_revision = '319bae16dc67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('combats_active_id_fkey', 'combats', type_='foreignkey')
    op.drop_column('combats', 'active_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combats', sa.Column('active_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('combats_active_id_fkey', 'combats', 'crews', ['active_id'], ['id'])
    # ### end Alembic commands ###
