"""remake Crew.action field

Revision ID: d07cbbd11c26
Revises: 
Create Date: 2023-04-23 18:24:44.466492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd07cbbd11c26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crews', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crews', 'actions', ['action_id'], ['id'])
    op.drop_column('crews', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crews', sa.Column('action', postgresql.ENUM('Attack', 'Dodge', 'FoolGiveUp', 'SmartGiveUp', 'SelfDestruct', name='action'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crews', type_='foreignkey')
    op.drop_column('crews', 'action_id')
    # ### end Alembic commands ###
