"""fourth try of reimpl combat-crew relationships

Revision ID: deb477523e15
Revises: 9af95301cdeb
Create Date: 2023-04-22 16:51:10.735734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb477523e15'
down_revision = '9af95301cdeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crews', sa.Column('combat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crews', 'combats', ['combat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crews', type_='foreignkey')
    op.drop_column('crews', 'combat_id')
    # ### end Alembic commands ###
