"""second try of reimpl combat-crew relationships

Revision ID: fba971eb713d
Revises: b0a996c54ee4
Create Date: 2023-04-22 16:31:34.634937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba971eb713d'
down_revision = 'b0a996c54ee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combats', sa.Column('active_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'combats', 'crews', ['active_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'combats', type_='foreignkey')
    op.drop_column('combats', 'active_id')
    # ### end Alembic commands ###
